Adding SplashScreen
Algo-Phantoms/Algo-Phantoms-Android pull request #22
Opened 2021-03-25 02:37 UTC by Shreyash41

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

### YES

### Description

Added Modern Splash Screen Feature in Algo-Phantoms Android.
- Added 2 Photos for logo and background 
- Added New Bold Text 
- Added New Splashscreen.kt file
- Changes in SplashScreen.xml file, Strings.xml file, themes.xml
- Added dimes folder for setting dimensions.
- Added SplashScreen to AndroidManifest.

Everything is working fine.

#### Note : Please set Android Version: 10
Appetize.io | [App Review](https://appetize.io/app/01vete7vruckmykzez25127af0)

| Smartphone Info  | Android Version |
| ------------- | ------------- |
|  OnePlus 7  |  Android 10  |

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.

## Related Issues or Pull Requests

#11

2021-03-25 02:43 UTC, Shreyash41 commented
@dheerajkotwani @tarun26091999 Sir, can you Please review my PR.

2021-03-29 16:46 UTC, dheerajkotwani commented
@Shreyash41 add the screenshot for the Splash Screen you have made.

2021-03-30 08:08 UTC, Shreyash41 commented
@dheerajkotwani Sir, Please Review my PR. I have added the screenshot of Splash Screen.

2021-03-30 08:19 UTC, carotkut94 requested changes

2021-03-30 08:19 UTC, carotkut94 commented on app/src/main/java/com/algo/phantoms/algo_phantoms/activities/SplashScreenActivity.kt
> +        @Suppress("DEPRECATION")
do not use deprecated methods migrate this code to `Handler(Looper.getMainLooper()).postDelayed({},2500)`

2021-03-30 08:19 UTC, carotkut94 commented on app/src/main/java/com/algo/phantoms/algo_phantoms/utils/MSPTextViewBold.kt
> +package com.algo.phantoms.algo_phantoms.utils
fonts can be directly applied to TextView by styles, or using font attributes, no need of this custom text view

2021-03-30 08:19 UTC, carotkut94 commented on app/src/main/res/layout/activity_splash_screen.xml
> +        android:layout_marginBottom="32dp"
move dimens to `dimens.xml`

2021-03-30 08:19 UTC, carotkut94 commented on app/src/main/res/layout/activity_splash_screen.xml
> +    <com.algo.phantoms.algo_phantoms.utils.MSPTextViewBold
replace it with TextView and apply in styles with custom font.

2021-03-30 08:19 UTC, carotkut94 commented on app/src/main/res/layout/activity_splash_screen.xml
> +    </com.algo.phantoms.algo_phantoms.utils.MSPTextViewBold>
empty views, which doesn't have any child should end with `<TextView />` instead of `<TextView></TextView>`

2021-03-30 17:40 UTC, Shreyash41 commented
@carotkut94 @dheerajkotwani Thanks sir for your time. I have resolved conflicts and Added a new Screenshot to compare New with Old. Please review my PR.

2021-04-02 13:07 UTC, merged